name: Audit

on:
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: '0 10 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Use Node.js LTS
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
      with:
        node-version: lts/*

    - name: Check Vulnerabilities
      run: npm audit --production --audit-level=moderate