name: Auto Responder for New Issues
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Process Label Action
        uses: hramos/respond-to-issue-based-on-label@a366dfe725db739c4522391dd1cb3daa9cb399d5 # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/label-actions.yml'
